/* ALTA ZERO · listing copy. Hero listings by archive number, plus category templates. */

const HERO = {
  '001':{desc:"Washed soft before it ever reaches you, so it arrives with the ease a good tee usually takes a whole summer to earn. Oversized through the body with a lived in hand you feel the second it goes on.",mat:"100% cotton, 250gsm, garment washed",fit:"Oversized, relaxed, true to size",care:"Machine wash cold. Hang dry to hold the wash. Warm iron reverse only."},
  '005':{desc:"A boxy cut in a mid heavy 260gsm cotton, run through a vintage wash so the color settles into the fabric instead of sitting on top of it. This is the everyday piece that keeps ending up in the photo you actually like.",mat:"100% cotton, 260gsm, vintage washed",fit:"Boxy, slightly cropped, true to size",care:"Machine wash cold inside out. Hang dry. Warm iron reverse only."},
  '015':{desc:"Brushed to a suede soft hand that makes it hard to reach for anything else, cut clean and light for the warm months. This is the one you buy in three colors the moment you feel it.",mat:"100% sueded cotton, 190gsm",fit:"Regular, lightly relaxed, true to size",care:"Machine wash cold. Hang dry. Do not iron at high heat."},
  '016':{desc:"A heavy 340gsm waffle knit with real texture in the hand, finished in a mineral wash that gives every piece its own broken in tone. Substantial, oversized, and quietly the most interesting blank in the room.",mat:"100% cotton waffle knit, 340gsm, mineral washed",fit:"Oversized, relaxed, true to size",care:"Machine wash cold separately on the first wash. Hang dry. Do not bleach."},
  '018':{desc:"Boxy and heavy at 310gsm, finished with a raw edge and a mineral wash so no two pieces land exactly alike. Structured enough to stand on its own, worn in enough to feel like yours from day one.",mat:"100% cotton, 310gsm, mineral washed, raw edge",fit:"Boxy, true to size. Size up for oversized",care:"Machine wash cold inside out. Hang dry. Do not bleach."},
  '020':{desc:"This is the tee we built the whole archive around. A dense 305gsm cotton with enough body to hold a boxy line on its own, the kind of blank that quietly outlasts everything else in the drawer.",mat:"100% heavyweight cotton, 305gsm",fit:"Boxy, structured, true to size. Size up for a fuller drape",care:"Machine wash cold inside out. Hang dry. Warm iron reverse only."},
  '027':{desc:"A proper oversized long sleeve in a full bodied 305gsm cotton, built to layer or stand alone when the light drops. The easy answer for the in between months, offered in the deepest color run of any long sleeve we make.",mat:"100% cotton, 305gsm",fit:"Oversized, relaxed, true to size",care:"Machine wash cold inside out. Hang dry. Warm iron reverse only."},
  '035':{desc:"Dense 350gsm cotton with real weight in the sleeve, the long sleeve you keep reaching past lighter ones for. Clean, considered, and built to wear for years.",mat:"100% heavyweight cotton, 350gsm",fit:"Regular, slightly relaxed, true to size",care:"Machine wash cold inside out. Hang dry. Warm iron reverse only."},
  '048':{desc:"A 400gsm brushed fleece crew with the kind of weight you feel the moment it goes on, cut clean with a set ribbed collar that holds its shape. The quiet cornerstone of a cold weather rotation.",mat:"Cotton rich brushed fleece, 400gsm",fit:"Classic crew, relaxed, true to size",care:"Machine wash cold inside out. Hang or tumble low."},
  '051':{desc:"An easy oversized hood in a soft 350gsm fleece, offered in the deepest color run in the archive. The everyday layer that goes with everything and asks nothing of you.",mat:"Cotton rich fleece, 350gsm",fit:"Oversized, relaxed, true to size",care:"Machine wash cold inside out. Hang or tumble low."},
  '054':{desc:"The flagship hood. A dense 430gsm fleece brushed soft on the inside, with a roomy hood and ribbed cuffs that keep their shape wash after wash. A ten year piece you keep reaching for past newer things.",mat:"Cotton rich heavyweight fleece, 430gsm",fit:"Relaxed, roomy hood, true to size. Size up for oversized",care:"Machine wash cold inside out. Hang or tumble low."},
  '063':{desc:"The heaviest piece we make, a monumental 530gsm fleece that stands almost on its own. For the coldest mornings and the people who want to feel the weight of what they are wearing.",mat:"Cotton rich heavyweight fleece, 530gsm",fit:"Oversized, structured hood, true to size",care:"Machine wash cold inside out. Hang or tumble low."},
  '064':{desc:"A tapered fleece jogger in a substantial 345gsm loopback, cut clean with a fit that reads considered off the couch and out the door. The bottom half of the uniform.",mat:"Cotton rich fleece, 345gsm",fit:"Tapered jogger, relaxed through the thigh, true to size",care:"Machine wash cold inside out. Hang or tumble low."},
  '065':{desc:"A heavy 430gsm sweatpant cut with a clean straight leg, none of the tapered gym look, all quiet weight and drape. The pair you end up living in.",mat:"Cotton rich heavyweight fleece, 430gsm",fit:"Straight leg, relaxed, true to size",care:"Machine wash cold inside out. Hang or tumble low."},
  '080':{desc:"A heavyweight cotton pant with a full wide leg and a paneled line that holds its shape all day. Structured, easy, and cut to move the way you actually do.",mat:"100% heavyweight cotton, 390gsm",fit:"Wide leg, relaxed, true to size",care:"Machine wash cold inside out. Hang dry. Warm iron."},
  '092':{desc:"A dense 500gsm fleece short with real substance, the warm weather half of the heavyweight family. Sits clean, wears soft, and outlasts every thin short in the drawer.",mat:"Cotton rich heavyweight fleece, 500gsm",fit:"Relaxed, mid length, true to size",care:"Machine wash cold inside out. Hang or tumble low."},
  '097':{desc:"A textured waffle knit short finished in a mineral wash so every pair carries its own tone. Easy, elevated, and the kind of warm weather piece that quietly reads expensive.",mat:"100% cotton waffle knit, 340gsm, mineral washed",fit:"Relaxed, mid length, true to size",care:"Machine wash cold separately on the first wash. Hang dry. Do not bleach."},
  '111':{desc:"A proper heavyweight denim jacket at 543gsm, run through a vintage wash so it lands already worn to that perfect year three fade. The layer you buy once and hand down.",mat:"100% cotton denim, 543gsm, vintage washed",fit:"Regular, structured, true to size. Size up to layer",care:"Machine wash cold inside out separately. Hang dry. Warm iron."}
};

const TPL = {
  'Tee':{desc:"A clean cotton tee cut for everyday wear, finished to feel broken in from the first pull. Wordless, considered, built to become the one you reach for without thinking.",mat:"100% cotton. Weight listed per piece",fit:"True to size. Boxy and oversized styles noted on the product",care:"Machine wash cold inside out. Hang dry. Warm iron reverse only."},
  'Long Sleeve':{desc:"A mid weight cotton long sleeve built to layer or stand alone when the light drops. The quiet piece that becomes the most worn thing you own.",mat:"100% cotton. Weight listed per piece",fit:"Regular, slightly relaxed, true to size",care:"Machine wash cold inside out. Hang dry. Warm iron reverse only."},
  'Hoodie':{desc:"A soft brushed fleece hood with real weight in the hand and a roomy, easy fit. Clean lines, no loud branding, the layer that quietly does everything.",mat:"Cotton rich fleece. Weight listed per piece",fit:"Relaxed, true to size. Size up for an oversized drape",care:"Machine wash cold inside out. Hang or tumble low."},
  'Crewneck':{desc:"A brushed fleece crew cut clean with a set ribbed collar that holds its shape. The understated cornerstone you layer over everything.",mat:"Cotton rich fleece. Weight listed per piece",fit:"Classic crew, relaxed, true to size",care:"Machine wash cold inside out. Hang or tumble low."},
  'Polo':{desc:"A considered cotton polo with a clean collar and an easy drop shoulder line. Elevated without trying, the piece that dresses an outfit up in one move.",mat:"Cotton pique or jersey. Weight listed per piece",fit:"Regular, true to size",care:"Machine wash cold. Hang dry. Warm iron."},
  'Shirt':{desc:"An easy short sleeve camp shirt with a relaxed boxy body and a clean open collar. The warm weather layer you throw over a tee and forget about.",mat:"Cotton. Weight listed per piece",fit:"Boxy, relaxed, true to size",care:"Machine wash cold. Hang dry. Warm iron."},
  'Pants':{desc:"A heavyweight cotton pant cut clean, built to hold its line all day and move the way you do. Structured, easy, quietly durable.",mat:"100% cotton. Weight listed per piece",fit:"True to size. Leg shape noted on the product",care:"Machine wash cold inside out. Hang dry. Warm iron."},
  'Sweatpants':{desc:"A brushed fleece sweatpant with real weight and a considered fit that reads good off the couch and out the door. The bottom half of the uniform.",mat:"Cotton rich fleece. Weight listed per piece",fit:"True to size. Leg shape noted on the product",care:"Machine wash cold inside out. Hang or tumble low."},
  'Shorts':{desc:"An easy warm weather short in a washed finish that carries its own tone. Sits clean, wears soft, and outlasts the thin ones every time.",mat:"Cotton. Weight listed per piece",fit:"Relaxed, mid length, true to size",care:"Machine wash cold inside out. Hang dry. Warm iron if needed."},
  'Jacket':{desc:"A heavyweight layer built to last, washed in so it lands already worn to that perfect fade. The kind of jacket you buy once and hand down.",mat:"Cotton or cotton denim. Weight listed per piece",fit:"Regular, structured, true to size. Size up to layer",care:"Machine wash cold inside out separately. Hang dry. Warm iron."},
  'Vest':{desc:"A clean full zip vest for the shoulder season, easy over a tee or under a shell. The quiet layer that adds warmth without bulk.",mat:"Cotton with mesh lining. Weight listed per piece",fit:"Regular, true to size",care:"Machine wash cold inside out. Hang dry."},
  'Tank':{desc:"A cotton muscle tank cut clean with a spliced panel line, built for the warmest days and the gym alike. Simple, wordless, done right.",mat:"100% cotton. Weight listed per piece",fit:"Regular, true to size",care:"Machine wash cold. Hang dry."}
};

function listingFor(p){
  const base = HERO[p.n] || TPL[p.cat] || TPL['Tee'];
  return base;
}
